# Generated by Django 4.1.7 on 2023-03-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=9),
        ),
    ]
