# Generated by Django 4.1.7 on 2023-03-26 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
    ]
